### ISSUE TITLE
i7 6700支持吗

### ISSUE THREAD

**Issue by wangheng669** [predatorq/OC-DELL-OptiPlex7040MICRO#1]

**Comment by predatorq** [comment]
是skylake的桌面端cpu应该都没有问题

**Comment by predatorq** [comment]
如果你测试成功的话可以来这儿提一下

**Comment by wangheng669** [comment]
好的,有开启跑码吗,支持双屏吧

**Comment by predatorq** [comment]
跑码默认开的, 双屏没做, 主要hdmi设置比较麻烦, 而且6代intel U的hdmi输出似乎没有4k60的选项感觉没啥必要[(相关链接)](https://ark.intel.com/content/www/cn/zh/ark/products/88196/intel-core-i76700-processor-8m-cache-up-to-4-00-ghz.html)

**Comment by wangheng669** [comment]
你是用的核显是吧,我这个电脑上有个gtx1650会有影响吗

**Comment by predatorq** [comment]
- 我这个efi适用于micro机子, 是7040系列里最小的, 你那个能装1650应该是大型塔式的, efi能否使用我不知道(usb定制等在bigsur的某个版本后应该会出问题), 建议找找看别的efi或者自己改.
- 另外1650这类新的英伟达卡hackintosh本身就无法使用的.

**Comment by wangheng669** [comment]
嗯感谢
